from __future__ import annotations

import urllib.parse
from datetime import datetime
from typing import TypedDict

from pydantic import BaseModel, ConfigDict, Field, HttpUrl


class FailureReportEntry(TypedDict):
    url: str
    continue_fail_count: int
    error_reason: str | None
    updated_at: int
    created_at: int
    has_content: bool


class FailureReport(TypedDict):
    generated_at: int
    generated_at_iso: str
    total: int
    failing: int
    entries: list[FailureReportEntry]


class Author(BaseModel):
    name: str
    url: HttpUrl | None = None
    avatar: HttpUrl | None = None


class Source(BaseModel):
    """JSON Feed `_source` extension: where this item originally came from.

    Critical when one aggregated feed merges many source blogs — without it,
    readers can't tell which blog a post belongs to.
    """

    title: str | None = None
    url: HttpUrl | None = None  # the source feed URL
    home_page_url: HttpUrl | None = None  # the source site URL


class FeedItem(BaseModel):
    # Allow `_source` (JSONFeed extension) by populating via alias.
    model_config = ConfigDict(populate_by_name=True)

    id: str
    url: HttpUrl
    title: str
    content_text: str | None = None
    content_html: str | None = None
    summary: str | None = None
    date_published: datetime
    author: Author | None = None
    tags: list[str] = Field(default_factory=list)
    language: str | None = None
    image: HttpUrl | None = None  # Main image URL
    external_url: HttpUrl | None = None  # For linkblog-style entries
    source: Source | None = Field(
        default=None,
        alias="_source",
        serialization_alias="_source",
    )


class Feed(BaseModel):
    version: str = "https://jsonfeed.org/version/1.1"
    title: str
    description: str | None = None
    home_page_url: HttpUrl | None = None
    feed_url: HttpUrl | None = None
    items: list[FeedItem]
    language: str | None = None
    user_comment: str | None = None

    @classmethod
    def create_from_items(
        cls,
        feed_name: str,
        items: list[FeedItem],
        base_url: str,
    ) -> Feed:
        """Create a Feed from items using an explicit release base URL."""
        feed_url = f"{base_url}/download/latest/{urllib.parse.quote(feed_name)}.json"
        home_url = f"{base_url}/tag/latest"

        return cls.model_validate(
            {
                "title": feed_name,
                "items": sorted(
                    items, key=lambda item: item.date_published, reverse=True
                ),
                "description": f"Aggregated feed for {feed_name}",
                "home_page_url": home_url,
                "feed_url": feed_url,
                "user_comment": "Generated by FeedForger",
                "language": None,
            }
        )


class FeedFilter(BaseModel):
    model_config = ConfigDict(extra="forbid")

    title: str = Field(min_length=1)
    invert: bool = False  # whether to invert the match


class FeedConfig(BaseModel):
    urls: list[str]
    filters: list[FeedFilter] = Field(default_factory=list)
    fulfill: bool = False  # whether to fetch content for each item


class RecipeCollection(BaseModel):
    recipes: dict[str, FeedConfig]
