from datetime import UTC, datetime, timedelta
from pathlib import Path

import pytest

from feedforger.models import Feed, FeedItem
from feedforger.settings import Settings


def test_settings_owns_all_path_ttl_and_window_defaults() -> None:
    settings = Settings()

    assert settings.recipes_path == Path("recipes")
    assert settings.output_dir == Path("outputs")
    assert settings.report_path == Path("cache/failure_report.json")
    assert settings.db_path == Path("cache/feeds.sqlite")
    assert settings.since == timedelta(days=7)
    assert settings.feed_ttl == timedelta(minutes=30)
    assert settings.article_ttl == timedelta(days=30)
    assert settings.cleanup_retention == timedelta(days=7)
    assert settings.request_timeout == 15.0


def test_settings_resolves_explicit_and_environment_base_urls() -> None:
    explicit = Settings.from_sources(
        env={
            "FEEDFORGER_BASE_URL": "https://env.example/releases",
            "GITHUB_REPOSITORY": "example/env-repo",
        },
        base_url="https://flag.example/releases",
    )
    from_environment = Settings.from_sources(
        env={"FEEDFORGER_BASE_URL": "https://env.example/releases"}
    )
    from_repository = Settings.from_sources(
        env={"GITHUB_REPOSITORY": "example/repository"}
    )

    assert explicit.base_url == "https://flag.example/releases"
    assert from_environment.base_url == "https://env.example/releases"
    assert from_repository.base_url == (
        "https://github.com/example/repository/releases"
    )


def test_settings_rejects_invalid_explicit_values() -> None:
    with pytest.raises(ValueError, match="max_concurrent must be positive"):
        Settings.from_sources(env={}, max_concurrent=0)
    with pytest.raises(ValueError, match="request_timeout must be positive"):
        Settings.from_sources(env={}, request_timeout=0.0)
    with pytest.raises(ValueError, match=r"base_url must be an HTTP\(S\) URL"):
        Settings.from_sources(env={}, base_url="")


def test_feed_serialization_uses_explicit_base_url() -> None:
    settings = Settings(base_url="https://feeds.example/releases")
    item = FeedItem.model_validate(
        {
            "id": "item-1",
            "url": "https://source.example/item-1",
            "title": "Item 1",
            "date_published": datetime(2026, 7, 12, tzinfo=UTC),
        }
    )

    first = Feed.create_from_items(
        "My Feed",
        [item],
        base_url=settings.base_url,
    ).model_dump_json(indent=2, exclude_none=True, by_alias=True)
    second = Feed.create_from_items(
        "My Feed",
        [item],
        base_url=settings.base_url,
    ).model_dump_json(indent=2, exclude_none=True, by_alias=True)

    assert first == second
    assert (
        first
        == """{
  "version": "https://jsonfeed.org/version/1.1",
  "title": "My Feed",
  "description": "Aggregated feed for My Feed",
  "home_page_url": "https://feeds.example/releases/tag/latest",
  "feed_url": "https://feeds.example/releases/download/latest/My%20Feed.json",
  "items": [
    {
      "id": "item-1",
      "url": "https://source.example/item-1",
      "title": "Item 1",
      "date_published": "2026-07-12T00:00:00Z",
      "tags": []
    }
  ],
  "user_comment": "Generated by FeedForger"
}"""
    )
