import asyncio
from datetime import timedelta
from pathlib import Path

import pytest

from feedforger.app import run_build
from feedforger.content_store import InMemoryContentStore

FIXTURES_DIR = Path(__file__).parent / "fixtures"

EXPECTED_OUTPUT = """{
  "version": "https://jsonfeed.org/version/1.1",
  "title": "Fixture",
  "description": "Aggregated feed for Fixture",
  "home_page_url": "https://github.com/RoCry/feedforger/releases/tag/latest",
  "feed_url": "https://github.com/RoCry/feedforger/releases/download/latest/Fixture.json",
  "items": [
    {
      "id": "urn:fixture:html",
      "url": "https://source.example/html-item",
      "title": "HTML item",
      "content_html": "<article><p>Hello <strong>world</strong>.</p></article>",
      "summary": "Hello world .",
      "date_published": "2026-07-10T12:00:00Z",
      "author": {
        "name": "ada@example.com (Ada)"
      },
      "tags": [
        "Python"
      ],
      "language": "en",
      "image": "https://source.example/thumbnail.jpg",
      "_source": {
        "title": "Fixture Source",
        "url": "https://fixture.example/feed.xml",
        "home_page_url": "https://source.example/"
      }
    },
    {
      "id": "urn:fixture:text",
      "url": "https://source.example/text-item",
      "title": "Text item",
      "content_text": "Plain fixture summary.",
      "date_published": "2026-07-09T08:30:00Z",
      "tags": [],
      "language": "en",
      "image": "https://source.example/enclosure.png",
      "_source": {
        "title": "Fixture Source",
        "url": "https://fixture.example/feed.xml",
        "home_page_url": "https://source.example/"
      }
    }
  ],
  "user_comment": "Generated by FeedForger"
}"""


def test_build_fixture_output_is_byte_identical(
    tmp_path: Path,
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    monkeypatch.delenv("FEEDFORGER_BASE_URL", raising=False)
    monkeypatch.delenv("GITHUB_REPOSITORY", raising=False)
    feed_url = "https://fixture.example/feed.xml"
    recipes_path = tmp_path / "recipes.toml"
    recipes_path.write_text(
        '[recipes.Fixture]\nurls = ["https://fixture.example/feed.xml"]\n'
    )
    store = InMemoryContentStore(
        responses={feed_url: [(FIXTURES_DIR / "characterization_feed.xml").read_text()]}
    )

    async def build_fixture() -> None:
        await run_build(
            store=store,
            recipes_path=recipes_path,
            output_dir=tmp_path / "outputs",
            since=timedelta(days=36500),
        )

    asyncio.run(build_fixture())

    output = tmp_path / "outputs" / "Fixture.json"
    assert output.read_bytes() == EXPECTED_OUTPUT.encode()
