name: Feed Aggregator

on:
  schedule:
    - cron: '0 */4 * * *'  # Run every 4 hours
  workflow_dispatch:  # Allow manual trigger

jobs:
  aggregate-feeds:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
    - uses: actions/checkout@v4

    - name: Install uv
      uses: astral-sh/setup-uv@v5
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version-file: "pyproject.toml"
    
    - name: Install dependencies
      run: |
        uv sync --all-extras --dev

    - name: Restore cache
      uses: actions/cache/restore@v4
      with:
        path: cache/
        key: feed-cache-${{ github.run_id }}
        restore-keys: |
          feed-cache-

    - name: Run feed aggregator
      run: uv run main.py
    
    - name: Save cache
      uses: actions/cache/save@v4
      with:
        path: cache/
        key: feed-cache-${{ github.run_id }}
    
    - name: Commit and push changes
      run: |
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git add outputs/
        git commit -m "Update feeds" || exit 0
        git push 