name: Feed Aggregator

on:
  schedule:
    - cron: '45 * * * *' # every hour at 45 min
  workflow_dispatch:  # Allow manual trigger
  push:
    branches:
      - deploy

jobs:
  aggregate-feeds:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
    - uses: actions/checkout@v4
      with:
        ref: deploy

    - name: Install uv
      uses: astral-sh/setup-uv@v5
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version-file: "pyproject.toml"
    
    - name: Install dependencies
      run: |
        uv sync --all-extras --dev

    - name: Restore cache
      uses: actions/cache/restore@v4
      with:
        path: cache/
        key: feed-cache-${{ github.run_id }}
        restore-keys: |
          feed-cache-

    - name: Set NOW variable
      id: set_now
      run: |
        echo "NOW=$(date -u '+%Y-%m-%d %H:%M:%S UTC')" >> $GITHUB_ENV

    - name: Run feed forger
      run: uv run main.py
    
    - name: Save cache
      uses: actions/cache/save@v4
      with:
        path: cache/
        key: feed-cache-${{ github.run_id }}
    
    - name: Create Release
      uses: softprops/action-gh-release@v2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        name: "Feeds Update ${{ env.NOW }}"
        tag_name: latest
        files: |
          outputs/*
          cache/feeds.sqlite
        prerelease: false 